
const parser = [

{"index":10, "identifier":"ID_WEB_Temperatur_TVL", "description":"Vorlauftemperatur Heizkreis", "conversion":"Wert / 10", "type":"°C"},
{"index":11, "identifier":"ID_WEB_Temperatur_TRL ", "description":"Rücklauftemperatur Heizkreis", "conversion":"Wert / 10", "type":"°C"},
{"index":12, "identifier":"ID_WEB_Sollwert_TRL_HZ", "description":"Rücklauf-Soll Heizkreis", "conversion":"Wert / 10", "type":"°C"},
{"index":13, "identifier":"ID_WEB_Temperatur_TRL_ext", "description":"Rücklauftemperatur im Trennspeicher.", "conversion":"Wert / 10", "type":"°C"},
{"index":14, "identifier":"ID_WEB_Temperatur_THG", "description":"Heisgastemperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":15, "identifier":"ID_WEB_Temperatur_TA", "description":"Aussentemperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":16, "identifier":"ID_WEB_Mitteltemperatur", "description":"Durchschnittstemperatur Aussen über 24 h (Funktion Heizgrenze)", "conversion":"Wert / 10", "type":"°C"},
{"index":17, "identifier":"ID_WEB_Temperatur_TBW", "description":"Warmwasser Ist-Temperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":18, "identifier":"ID_WEB_Einst_BWS_akt", "description":"Warmwasser Soll-Temperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":19, "identifier":"ID_WEB_Temperatur_TWE", "description":"Wärmequellen-Eintrittstemperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":20, "identifier":"ID_WEB_Temperatur_TWA", "description":"Wärmequellen-Austrittstemperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":21, "identifier":"ID_WEB_Temperatur_TFB1 ", "description":"Mischkreis 1 Vorlauftemperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":22, "identifier":"ID_WEB_Sollwert_TVL_MK1", "description":"Mischkreis 1 Vorlauf-Soll-Temperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":23, "identifier":"ID_WEB_Temperatur_RFV  ", "description":"Raumtemperatur Raumstation 1", "conversion":"Wert / 10", "type":"°C"},
{"index":24, "identifier":"ID_WEB_Temperatur_TFB2", "description":"Mischkreis 2 Vorlauftemperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":25, "identifier":"ID_WEB_Sollwert_TVL_MK2", "description":"Mischkreis 2 Vorlauf-Soll-Temperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":26, "identifier":"ID_WEB_Temperatur_TSK", "description":"Fühler Solarkollektor", "conversion":"Wert / 10", "type":"°C"},
{"index":27, "identifier":"ID_WEB_Temperatur_TSS", "description":"Fühler Solarspeicher", "conversion":"Wert / 10", "type":"°C"},
{"index":28, "identifier":"ID_WEB_Temperatur_TEE", "description":"Fühler externe Energiequelle", "conversion":"Wert / 10", "type":"°C"},
{"index":29, "identifier":"ID_WEB_ASDin", "description":"Eingang ""Abtauende, Soledruck, Durchfluss"""", "conversion":"Keine", "type":"Boolean"},
{"index":30, "identifier":"ID_WEB_BWTin", "description":"Eingang ""Brauchwarmwasserthermostat"""", "conversion":"Keine", "type":"Boolean"},
{"index":31, "identifier":"ID_WEB_EVUin", "description":"Eingang ""EVU Sperre"""", "conversion":"Keine", "type":"Boolean"},
{"index":32, "identifier":"ID_WEB_HDin", "description":"Eingang ""Hochdruck Kältekreis"""", "conversion":"Keine", "type":"Boolean"},
{"index":33, "identifier":"ID_WEB_MOTin", "description":"Eingang ""Motorschutz OK"""", "conversion":"Keine", "type":"Boolean"},
{"index":34, "identifier":"ID_WEB_NDin", "description":"Eingang ""Niederdruck"""", "conversion":"Keine", "type":"Boolean"},
{"index":35, "identifier":"ID_WEB_PEXin", "description":"Eingang ""Überwachungskontakt für Potentiostat"""", "conversion":"Keine", "type":"Boolean"},
{"index":36, "identifier":"ID_WEB_SWTin", "description":"Eingang ""Schwimmbadthermostat"""", "conversion":"Keine", "type":"Boolean"},
{"index":37, "identifier":"ID_WEB_AVout", "description":"Ausgang ""Abtauventil"""", "conversion":"Keine", "type":"Boolean"},
{"index":38, "identifier":"ID_WEB_BUPout", "description":"Ausgang ""Brauchwasserpumpe/Umstellventil"""", "conversion":"Keine", "type":"Boolean"},
{"index":39, "identifier":"ID_WEB_HUPout", "description":"Ausgang ""Heizungsumwälzpumpe"""", "conversion":"Keine", "type":"Boolean"},
{"index":40, "identifier":"ID_WEB_MA1out", "description":"Ausgang ""Mischkreis 1 Auf"""", "conversion":"Keine", "type":"Boolean"},
{"index":41, "identifier":"ID_WEB_MZ1out", "description":"Ausgang ""Mischkreis 1 Zu"""", "conversion":"Keine", "type":"Boolean"},
{"index":42, "identifier":"ID_WEB_VENout", "description":"Ausgang ""Ventilation (Lüftung)"""", "conversion":"Keine", "type":"Boolean"},
{"index":43, "identifier":"ID_WEB_VBOout", "description":"Ausgang ""Solepumpe/Ventilator"""", "conversion":"Keine", "type":"Boolean"},
{"index":44, "identifier":"ID_WEB_VD1out", "description":"Ausgang ""Verdichter 1"""", "conversion":"Keine", "type":"Boolean"},
{"index":45, "identifier":"ID_WEB_VD2out", "description":"Ausgang ""Verdichter 2"""", "conversion":"Keine", "type":"Boolean"},
{"index":46, "identifier":"ID_WEB_ZIPout", "description":"Ausgang ""Zirkulationspumpe"""", "conversion":"Keine", "type":"Boolean"},
{"index":47, "identifier":"ID_WEB_ZUPout", "description":"Ausgang ""Zusatzumwälzpumpe"""", "conversion":"Keine", "type":"Boolean"},
{"index":48, "identifier":"ID_WEB_ZW1out", "description":"Ausgang ""Steuersignal Zusatzheizung v. Heizung"""", "conversion":"Keine", "type":"Boolean"},
{"index":49, "identifier":"ID_WEB_ZW2SSTout", "description":"Ausgang ""Steuersignal Zusatzheizung/Störsignal"""", "conversion":"Keine", "type":"Boolean"},
{"index":50, "identifier":"ID_WEB_ZW3SSTout", "description":"Ausgang ""Zusatzheizung 3"""", "conversion":"Keine", "type":"Boolean"},
{"index":51, "identifier":"ID_WEB_FP2out", "description":"Ausgang ""Pumpe Mischkreis 2"""", "conversion":"Keine", "type":"Boolean"},
{"index":52, "identifier":"ID_WEB_SLPout", "description":"Ausgang ""Solarladepumpe"""", "conversion":"Keine", "type":"Boolean"},
{"index":53, "identifier":"ID_WEB_SUPout", "description":"Ausgang ""Schwimmbadpumpe"""", "conversion":"Keine", "type":"Boolean"},
{"index":54, "identifier":"ID_WEB_MZ2out", "description":"Ausgang ""Mischkreis 2 Zu"""", "conversion":"Keine", "type":"Boolean"},
{"index":55, "identifier":"ID_WEB_MA2out", "description":"Ausgang ""Mischkreis 2 Auf"""", "conversion":"Keine", "type":"Boolean"},
{"index":56, "identifier":"ID_WEB_Zaehler_BetrZeitVD1", "description":"Betriebsstunden Verdichter 1", "conversion":"Keine", "type":"Sekunden"},
{"index":57, "identifier":"ID_WEB_Zaehler_BetrZeitImpVD1", "description":"Impulse Verdichter 1", "conversion":"Keine", "type":"Impulse"},
{"index":58, "identifier":"ID_WEB_Zaehler_BetrZeitVD2", "description":"Betriebsstunden Verdichter 2", "conversion":"Keine", "type":"Sekunden"},
{"index":59, "identifier":"ID_WEB_Zaehler_BetrZeitImpVD2", "description":"Impulse Verdichter 2", "conversion":"Keine", "type":"Impulse"},
{"index":60, "identifier":"ID_WEB_Zaehler_BetrZeitZWE1", "description":"Betriebsstunden Zweiter Wärmeerzeuger 1", "conversion":"Keine", "type":"Sekunden"},
{"index":61, "identifier":"ID_WEB_Zaehler_BetrZeitZWE2", "description":"Betriebsstunden Zweiter Wärmeerzeuger 2", "conversion":"Keine", "type":"Sekunden"},
{"index":62, "identifier":"ID_WEB_Zaehler_BetrZeitZWE3", "description":"Betriebsstunden Zweiter Wärmeerzeuger 3", "conversion":"?? (Wert / 7200 = Stunden)", "type":"??"},
{"index":63, "identifier":"ID_WEB_Zaehler_BetrZeitWP", "description":"Betriebsstunden Wärmepumpe", "conversion":"Keine", "type":"Sekunden"},
{"index":64, "identifier":"ID_WEB_Zaehler_BetrZeitHz", "description":"Betriebsstunden Heizung", "conversion":"Keine", "type":"Sekunden"},
{"index":65, "identifier":"ID_WEB_Zaehler_BetrZeitBW", "description":"Betriebsstunden Warmwasser", "conversion":"Keine", "type":"Sekunden"},
{"index":66, "identifier":"ID_WEB_Zaehler_BetrZeitKue", "description":"Betriebsstunden Kühlung", "conversion":"Keine", "type":"Sekunden"},
{"index":67, "identifier":"ID_WEB_Time_WPein_akt", "description":"Wärmepumpe läuft seit", "conversion":"Keine", "type":"Sekunden"},
{"index":68, "identifier":"ID_WEB_Time_ZWE1_akt", "description":"Zweiter Wärmeerzeuger 1 läuft seit", "conversion":"Keine", "type":"Sekunden"},
{"index":69, "identifier":"ID_WEB_Time_ZWE2_akt", "description":"Zweiter Wärmeerzeuger 2 läuft seit", "conversion":"Keine", "type":"Sekunden"},
{"index":70, "identifier":"ID_WEB_Timer_EinschVerz", "description":"Netzeinschaltverzögerung", "conversion":"Keine", "type":"Sekunden"},
{"index":71, "identifier":"ID_WEB_Time_SSPAUS_akt", "description":"Schaltspielsperre Aus", "conversion":"Keine", "type":"Sekunden"},
{"index":72, "identifier":"ID_WEB_Time_SSPEIN_akt", "description":"Schaltspielsperre Ein", "conversion":"Keine", "type":"Sekunden"},
{"index":73, "identifier":"ID_WEB_Time_VDStd_akt", "description":"Verdichter-Standzeit", "conversion":"Keine", "type":"Sekunden"},
{"index":74, "identifier":"ID_WEB_Time_HRM_akt", "description":"Heizungsregler Mehr-Zeit", "conversion":"Keine", "type":"Sekunden"},
{"index":75, "identifier":"ID_WEB_Time_HRW_akt", "description":"Heizungsregler Weniger-Zeit", "conversion":"Keine", "type":"Sekunden"},
{"index":76, "identifier":"ID_WEB_Time_LGS_akt", "description":"Thermische Desinfektion läuft seit", "conversion":"Keine", "type":"Sekunden"},
{"index":77, "identifier":"ID_WEB_Time_SBW_akt", "description":"Sperre Warmwasser", "conversion":"Keine", "type":"Sekunden"},
{"index":78, "identifier":"ID_WEB_Code_WP_akt", "description":"Wärmepumpentyp", "conversion":"type_codes", "type":"Typenschlüssel"},
79;ID_WEB_BIV_Stufe_akt;Bivalenzstufe;1 = ein Verdichter darf laufen;
;;;2 = zwei Verdichter dürfen laufen;
;;;3 = zusätzlicher Wärmeerzeuger darf mitlaufen;
80;ID_WEB_WP_BZ_akt;Betriebszustand;0 = Heizen;
;;;1 = Warmwasser;
;;;2 = Schwimmbad / Photovoltaik;
;;;3 = EVU;
;;;4 = Abtauen;
;;;5 = Keine Anforderung;
;;;6 = Heizen ext. Energiequelle;
;;;7 = Kühlbetrieb ;
{"index":81, "identifier":"ID_WEB_SoftStand1", "description":"Softwarestand", "conversion":"ASCII z.B. 86 = V", "type":"ASCII"},
{"index":82, "identifier":"ID_WEB_SoftStand2", "description":"Softwarestand", "conversion":"ASCII z.B. 51 = 3", "type":"ASCII"},
{"index":83, "identifier":"ID_WEB_SoftStand3", "description":"Softwarestand", "conversion":"ASCII z.B. 46 = .", "type":"ASCII"},
{"index":84, "identifier":"ID_WEB_SoftStand4", "description":"Softwarestand", "conversion":"ASCII z.B. 55 = 7", "type":"ASCII"},
{"index":85, "identifier":"ID_WEB_SoftStand5", "description":"Softwarestand", "conversion":"ASCII z.B. 56 = 8", "type":"ASCII"},
{"index":86, "identifier":"ID_WEB_SoftStand6", "description":"Softwarestand", "conversion":"ASCII 0 = Nichts", "type":"ASCII"},
{"index":87, "identifier":"ID_WEB_SoftStand7", "description":"Softwarestand", "conversion":"ASCII 0 = Nichts", "type":"ASCII"},
{"index":88, "identifier":"ID_WEB_SoftStand8", "description":"Softwarestand", "conversion":"ASCII 0 = Nichts", "type":"ASCII"},
{"index":89, "identifier":"ID_WEB_SoftStand9", "description":"Softwarestand", "conversion":"ASCII 0 = Nichts", "type":"ASCII"},
{"index":90, "identifier":"ID_WEB_SoftStand10", "description":"Softwarestand", "conversion":"ASCII 0 = Nichts", "type":"ASCII"},
{"index":91, "identifier":"ID_WEB_AdresseIP_akt", "description":"IP Adresse", "conversion":"siehe Beispielcode unten", "type":"IP"},
{"index":92, "identifier":"ID_WEB_SubNetMask_akt", "description":"Subnetzmaske", "conversion":"siehe Beispielcode unten", "type":"IP"},
{"index":93, "identifier":"ID_WEB_Add_Broadcast", "description":"Broadcast Adresse", "conversion":"siehe Beispielcode unten", "type":"IP"},
{"index":94, "identifier":"ID_WEB_Add_StdGateway", "description":"Standard Gateway", "conversion":"siehe Beispielcode unten", "type":"IP"},
{"index":95, "identifier":"ID_WEB_ERROR_Time0", "description":"Zeitstempel Fehler 0 im Speicher", "conversion":"Keine", "type":"Unix Timestamp"},
{"index":96, "identifier":"ID_WEB_ERROR_Time1", "description":"Zeitstempel Fehler 1 im Speicher", "conversion":"Keine", "type":"Unix Timestamp"},
{"index":97, "identifier":"ID_WEB_ERROR_Time2", "description":"Zeitstempel Fehler 2 im Speicher", "conversion":"Keine", "type":"Unix Timestamp"},
{"index":98, "identifier":"ID_WEB_ERROR_Time3", "description":"Zeitstempel Fehler 3 im Speicher", "conversion":"Keine", "type":"Unix Timestamp"},
{"index":99, "identifier":"ID_WEB_ERROR_Time4", "description":"Zeitstempel Fehler 4 im Speicher", "conversion":"Keine", "type":"Unix Timestamp"},
{"index":100, "identifier":"ID_WEB_ERROR_Nr0", "description":"Fehlercode Fehler 0 im Speicher", "conversion":"Keine", "type":"Fehlercode"},
{"index":101, "identifier":"ID_WEB_ERROR_Nr1", "description":"Fehlercode Fehler 1 im Speicher", "conversion":"Keine", "type":"Fehlercode"},
{"index":102, "identifier":"ID_WEB_ERROR_Nr2", "description":"Fehlercode Fehler 2 im Speicher", "conversion":"Keine", "type":"Fehlercode"},
{"index":103, "identifier":"ID_WEB_ERROR_Nr3", "description":"Fehlercode Fehler 3 im Speicher", "conversion":"Keine", "type":"Fehlercode"},
{"index":104, "identifier":"ID_WEB_ERROR_Nr4", "description":"Fehlercode Fehler 4 im Speicher", "conversion":"Keine", "type":"Fehlercode"},
{"index":105, "identifier":"ID_WEB_AnzahlFehlerInSpeicher", "description":"Anzahl der Fehler im Speicher", "conversion":"Keine", "type":""},
{"index":106, "identifier":"ID_WEB_Switchoff_file_Nr0", "description":"Grund Abschaltung 0 im Speicher", "conversion":"switchoff_code", "type":"Abschaltcode"},
{"index":107, "identifier":"ID_WEB_Switchoff_file_Nr1", "description":"Grund Abschaltung 1 im Speicher", "conversion":"siehe Abschaltcode 0", "type":"Abschaltcode"},
{"index":108, "identifier":"ID_WEB_Switchoff_file_Nr2", "description":"Grund Abschaltung 2 im Speicher", "conversion":"siehe Abschaltcode 0", "type":"Abschaltcode"},
{"index":109, "identifier":"ID_WEB_Switchoff_file_Nr3", "description":"Grund Abschaltung 3 im Speicher", "conversion":"siehe Abschaltcode 0", "type":"Abschaltcode"},
{"index":110, "identifier":"ID_WEB_Switchoff_file_Nr4", "description":"Grund Abschaltung 4 im Speicher", "conversion":"siehe Abschaltcode 0", "type":"Abschaltcode"},
{"index":111, "identifier":"ID_WEB_Switchoff_file_Time0", "description":"Zeitstempel Abschaltung 0 im Speicher", "conversion":"Keine", "type":"Unix Zeitstempel"},
{"index":112, "identifier":"ID_WEB_Switchoff_file_Time1", "description":"Zeitstempel Abschaltung 1 im Speicher", "conversion":"Keine", "type":"Unix Zeitstempel"},
{"index":113, "identifier":"ID_WEB_Switchoff_file_Time2", "description":"Zeitstempel Abschaltung 2 im Speicher", "conversion":"Keine", "type":"Unix Zeitstempel"},
{"index":114, "identifier":"ID_WEB_Switchoff_file_Time3", "description":"Zeitstempel Abschaltung 3 im Speicher", "conversion":"Keine", "type":"Unix Zeitstempel"},
{"index":115, "identifier":"ID_WEB_Switchoff_file_Time4", "description":"Zeitstempel Abschaltung 4 im Speicher", "conversion":"Keine", "type":"Unix Zeitstempel"},
{"index":116, "identifier":"ID_WEB_Comfort_exists", "description":"Comfort Platine installiert", "conversion":"built_in", "type":"Boolean"},
{"index":117, "identifier":"ID_WEB_HauptMenuStatus_Zeile1", "description":"Status Zeile 1", "conversion":"status_code_1", "type":"Statuscode"},
{"index":118, "identifier":"ID_WEB_HauptMenuStatus_Zeile2", "description":"Status Zeile 2", "conversion":"0 = seit :", "type":"Statustext"},
{"index":119, "identifier":"ID_WEB_HauptMenuStatus_Zeile3", "description":"Status Zeile 3", "conversion":"status_code_2", "type":"Statuscode"},
{"index":120, "identifier":"ID_WEB_HauptMenuStatus_Zeit", "description":"Zeit seit / in (in kombination mit #118)", "conversion":"Keine", "type":"Sekunden"},
{"index":121, "identifier":"ID_WEB_HauptMenuAHP_Stufe", "description":"Stufe Ausheizprogramm", "conversion":"Keine", "type":""},
{"index":122, "identifier":"ID_WEB_HauptMenuAHP_Temp", "description":"Temperatur Ausheizprogramm", "conversion":"Wert * 0.1", "type":"°C"},
{"index":123, "identifier":"ID_WEB_HauptMenuAHP_Zeit", "description":"Laufzeit Ausheizprogramm", "conversion":"Keine", "type":"Sekunden"},
{"index":124, "identifier":"ID_WEB_SH_BWW", "description":"Brauchwasser Symbol", "conversion":"??", "type":"Boolean"},
{"index":125, "identifier":"ID_WEB_SH_HZ", "description":"Heizung Symbol", "conversion":"??", "type":"??"},
{"index":126, "identifier":"ID_WEB_SH_MK1", "description":"Mischkreis 1 Symbol", "conversion":"??", "type":"??"},
{"index":127, "identifier":"ID_WEB_SH_MK2", "description":"Mischkreis 2 Symbol", "conversion":"??", "type":"??"},
{"index":128, "identifier":"ID_WEB_Einst_Kurzrpgramm", "description":"Einstellung Kurzprogramm", "conversion":"??", "type":"??"},
{"index":129, "identifier":"ID_WEB_StatusSlave_1", "description":"Status Slave 1", "conversion":"??", "type":"??"},
{"index":130, "identifier":"ID_WEB_StatusSlave_2", "description":"Status Slave 2", "conversion":"??", "type":"??"},
{"index":131, "identifier":"ID_WEB_StatusSlave_3", "description":"Status Slave 3", "conversion":"??", "type":"??"},
{"index":132, "identifier":"ID_WEB_StatusSlave_4", "description":"Status Slave 4", "conversion":"??", "type":"??"},
{"index":133, "identifier":"ID_WEB_StatusSlave_5", "description":"Status Slave 5", "conversion":"??", "type":"??"},
{"index":134, "identifier":"ID_WEB_AktuelleTimeStamp", "description":"Aktuelle Zeit der Wärmepumpe", "conversion":"Keine", "type":"Unix Timestamp"},
{"index":135, "identifier":"ID_WEB_SH_MK3", "description":"Mischkreis 3 Symbol", "conversion":"??", "type":"??"},
{"index":136, "identifier":"ID_WEB_Sollwert_TVL_MK3", "description":"Mischkreis 3 Vorlauf-Soll-Temperatur", "conversion":"Wert * 0.1", "type":"°C"},
{"index":137, "identifier":"ID_WEB_Temperatur_TFB3", "description":"Mischkreis 3 Vorlauftemperatur", "conversion":"Wert * 0.1", "type":"°C"},
{"index":138, "identifier":"ID_WEB_MZ3out", "description":"Ausgang Mischkreis 3 Zu", "conversion":"Keine", "type":"Boolean"},
{"index":139, "identifier":"ID_WEB_MA3out", "description":"Ausgang Mischkreis 3 Auf", "conversion":"Keine", "type":"Boolean"},
{"index":140, "identifier":"ID_WEB_FP3out", "description":"Pumpe Mischkreis 3", "conversion":"Keine", "type":"Boolean"},
{"index":141, "identifier":"ID_WEB_Time_AbtIn", "description":"Zeit bis Abtauen", "conversion":"Keine", "type":"Sekunden"},
{"index":142, "identifier":"ID_WEB_Temperatur_RFV2", "description":"Raumtemperatur Raumstation 2", "conversion":"Wert * 0.1", "type":"°C"},
{"index":143, "identifier":"ID_WEB_Temperatur_RFV3", "description":"Raumtemperatur Raumstation 3", "conversion":"Wert * 0.1", "type":"°C"},
{"index":144, "identifier":"ID_WEB_SH_SW", "description":"Schaltuhr Schwimmbad Symbol", "conversion":"??", "type":"??"},
{"index":145, "identifier":"ID_WEB_Zaehler_BetrZeitSW", "description":"Betriebsstunden Schwimmbad", "conversion":"?? (Wert / 7200 = Stunden)", "type":"??"},
{"index":146, "identifier":"ID_WEB_FreigabKuehl", "description":"Freigabe Kühlung", "conversion":"Keine", "type":"Boolean"},
{"index":147, "identifier":"ID_WEB_AnalogIn", "description":"Analoges Eingangssignal", "conversion":"Wert / 100", "type":"V"},
{"index":148, "identifier":"ID_WEB_SonderZeichen", "description":"??", "conversion":"??", "type":"??"},
{"index":149, "identifier":"ID_WEB_SH_ZIP", "description":"Zirkulationspumpen Symbol", "conversion":"??", "type":"??"},
{"index":150, "identifier":"ID_WEB_WebsrvProgrammWerteBeobarten", "description":"??", "conversion":"??", "type":"??"},
{"index":151, "identifier":"ID_WEB_WMZ_Heizung", "description":"Wärmemengenzähler Heizung", "conversion":"Wert / 10", "type":"kWh"},
{"index":152, "identifier":"ID_WEB_WMZ_Brauchwasser", "description":"Wärmemengenzähler Brauchwasser", "conversion":"Wert / 10", "type":"kWh"},
{"index":153, "identifier":"ID_WEB_WMZ_Schwimmbad", "description":"Wärmemengenzähler Schwimmbad", "conversion":"Wert / 10", "type":"kWh"},
{"index":154, "identifier":"ID_WEB_WMZ_Seit", "description":"Wärmemengenzähler Gesamt", "conversion":"Wert / 10", "type":"kWh"},
{"index":155, "identifier":"ID_WEB_WMZ_Durchfluss", "description":"Wärmemengenzähler Durchfluss", "conversion":"Keine", "type":"l / h"},
{"index":156, "identifier":"ID_WEB_AnalogOut1", "description":"Analog Ausgang 1", "conversion":"Wert / 100", "type":"V"},
{"index":157, "identifier":"ID_WEB_AnalogOut2", "description":"Analog Ausgang 2", "conversion":"Wert / 100", "type":"V"},
{"index":158, "identifier":"ID_WEB_Time_Heissgas", "description":"Sperre zweiter Verdichter Heissgas", "conversion":"Keine", "type":"Sekunden"},
{"index":159, "identifier":"ID_WEB_Temp_Lueftung_Zuluft", "description":"Zulufttemperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":160, "identifier":"ID_WEB_Temp_Lueftung_Abluft", "description":"Ablufttemperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":161, "identifier":"ID_WEB_Zaehler_BetrZeitSolar", "description":"Betriebstundenzähler Solar  ", "conversion":"Keine", "type":"Sekunden"},
{"index":162, "identifier":"ID_WEB_AnalogOut3", "description":"Analog Ausgang 3", "conversion":"Wert / 100", "type":"V"},
{"index":163, "identifier":"ID_WEB_AnalogOut4", "description":"Analog Ausgang 4", "conversion":"Wert / 100", "type":"V"},
{"index":164, "identifier":"ID_WEB_Out_VZU", "description":"Zuluft Ventilator (Abtaufunktion)", "conversion":"Wert / 100", "type":"V"},
{"index":165, "identifier":"ID_WEB_Out_VAB", "description":"Abluft Ventilator", "conversion":"Wert / 100", "type":"V"},
{"index":166, "identifier":"ID_WEB_Out_VSK", "description":"Ausgang VSK", "conversion":"Keine", "type":"Boolean"},
{"index":167, "identifier":"ID_WEB_Out_FRH", "description":"Ausgang FRH", "conversion":"Keine", "type":"Boolean"},
{"index":168, "identifier":"ID_WEB_AnalogIn2", "description":"Analog Eingang 2", "conversion":"Wert / 100", "type":"V"},
{"index":169, "identifier":"ID_WEB_AnalogIn3", "description":"Analog Eingang 3", "conversion":"Wert / 100", "type":"V"},
{"index":170, "identifier":"ID_WEB_SAXin", "description":"Eingang SAX", "conversion":"Keine", "type":"Boolean"},
{"index":171, "identifier":"ID_WEB_SPLin", "description":"Eingang SPL", "conversion":"Keine", "type":"Boolean"},
{"index":172, "identifier":"ID_WEB_Compact_exists", "description":"Lüftungsplatine verbaut", "conversion":"built_in", "type":"Boolean"},
{"index":173, "identifier":"ID_WEB_Durchfluss_WQ", "description":"Durchfluss Wärmequelle", "conversion":"Keine", "type":"l / h"},
{"index":174, "identifier":"ID_WEB_LIN_exists", "description":"LIN BUS verbaut", "conversion":"built_in", "type":"Boolean"},
{"index":175, "identifier":"ID_WEB_LIN_ANSAUG_VERDAMPFER", "description":"Temperatur Ansaug Verdampfer", "conversion":"Wert / 10", "type":"°C"},
{"index":176, "identifier":"ID_WEB_LIN_ANSAUG_VERDICHTER", "description":"Temperatur Ansaug Verdichter", "conversion":"Wert / 10", "type":"°C"},
{"index":177, "identifier":"ID_WEB_LIN_VDH", "description":"Temperatur Verdichter Heizung", "conversion":"Wert / 10", "type":"°C"},
{"index":178, "identifier":"ID_WEB_LIN_UH", "description":"Überhitzung", "conversion":"Wert / 10", "type":"K"},
{"index":179, "identifier":"ID_WEB_LIN_UH_Soll", "description":"Überhitzung Soll ", "conversion":"Wert / 10", "type":"K"},
{"index":180, "identifier":"ID_WEB_LIN_HD", "description":"Hochdruck", "conversion":"Wert / 100", "type":"bar"},
{"index":181, "identifier":"ID_WEB_LIN_ND", "description":"Niederdruck", "conversion":"Wert / 100", "type":"bar"},
{"index":182, "identifier":"ID_WEB_LIN_VDH_out", "description":"Ausgang Verdichterheizung", "conversion":"Keine", "type":"Boolean"},
{"index":183, "identifier":"ID_WEB_HZIO_PWM", "description":"Steuersignal Umwälzpumpe", "conversion":"Wert / 10", "type":"%"},
{"index":184, "identifier":"ID_WEB_HZIO_VEN", "description":"Ventilator Drehzahl", "conversion":"Keine", "type":"U / min"},
{"index":185, "identifier":"ID_WEB_HZIO_EVU2", "description":"EVU 2", "conversion":"??", "type":"??"},
{"index":186, "identifier":"ID_WEB_HZIO_STB", "description":"Sicherheits-Tempeartur-Begrenzer Fussbodenheizung", "conversion":"Keine", "type":"Boolean"},
{"index":187, "identifier":"ID_WEB_SEC_Qh_Soll", "description":"Leistung Sollwert", "conversion":"Wert / 100", "type":"kWh"},
{"index":188, "identifier":"ID_WEB_SEC_Qh_Ist", "description":"Leistung Istwert", "conversion":"Wert / 100", "type":"kWh"},
{"index":189, "identifier":"ID_WEB_SEC_TVL_Soll", "description":"Temperatur Vorlauf Soll", "conversion":"Wert / 10", "type":"°C"},
{"index":190, "identifier":"ID_WEB_SEC_Software", "description":"Software Stand SEC Board", "conversion":"??", "type":"??"},
{"index":191, "identifier":"ID_WEB_SEC_BZ", "description":"Betriebszustand SEC Board", "conversion":"operating_state", "type":"Betriebszustand"},
{"index":192, "identifier":"ID_WEB_SEC_VWV", "description":"Vierwegeventil", "conversion":"??", "type":"??"},
{"index":193, "identifier":"ID_WEB_SEC_VD", "description":"Verdichterdrehzahl", "conversion":"Keine", "type":"U / min"},
{"index":194, "identifier":"ID_WEB_SEC_VerdEVI", "description":"Verdichtertemperatur EVI (Enhanced Vapour Injection)", "conversion":"Wert / 10", "type":"°C"},
{"index":195, "identifier":"ID_WEB_SEC_AnsEVI", "description":"Ansaugtemperatur EVI", "conversion":"Wert / 10", "type":"°C"},
{"index":196, "identifier":"ID_WEB_SEC_UEH_EVI", "description":"Überhitzung EVI", "conversion":"Wert / 10", "type":"K"},
{"index":197, "identifier":"ID_WEB_SEC_UEH_EVI_S", "description":"Überhitzung EVI Sollwert", "conversion":"Wert / 10", "type":"K"},
{"index":198, "identifier":"ID_WEB_SEC_KondTemp", "description":"Kondensationstemperatur", "conversion":"Wert / 10", "type":"°C"},
{"index":199, "identifier":"ID_WEB_SEC_FlussigEx", "description":"Flüssigtemperatur EEV (elektronisches Expansionsventil)", "conversion":"Wert / 10", "type":"°C"},
{"index":200, "identifier":"ID_WEB_SEC_UK_EEV", "description":"Unterkühlung EEV", "conversion":"Wert / 10", "type":"°C"},
{"index":201, "identifier":"ID_WEB_SEC_EVI_Druck", "description":"Druck EVI", "conversion":"Wert / 100", "type":"bar"},
{"index":202, "identifier":"ID_WEB_SEC_U_Inv", "description":"Spannung Inverter", "conversion":"Wert / 10", "type":"V"},
{"index":203, "identifier":"ID_WEB_Temperatur_THG_2", "description":"Temperarturfühler Heissgas 2", "conversion":"Wert / 10", "type":"°C"},
{"index":204, "identifier":"ID_WEB_Temperatur_TWE_2", "description":"Temperaturfühler Wärmequelleneintritt 2", "conversion":"Wert / 10", "type":"°C"},
{"index":205, "identifier":"ID_WEB_LIN_ANSAUG_VERDAMPFER_2", "description":"Ansaugtemperatur Verdampfer 2", "conversion":"Wert / 10", "type":"°C"},
{"index":206, "identifier":"ID_WEB_LIN_ANSAUG_VERDICHTER_2", "description":"Ansaugtemperatur Verdichter 2", "conversion":"Wert / 10", "type":"°C"},
{"index":207, "identifier":"ID_WEB_LIN_VDH_2", "description":"Temperatur Verdichter 2 Heizung", "conversion":"Wert / 10", "type":"°C"},
{"index":208, "identifier":"ID_WEB_LIN_UH_2", "description":"Überhitzung 2", "conversion":"Wert / 10", "type":"K"},
{"index":209, "identifier":"ID_WEB_LIN_UH_Soll_2", "description":"Überhitzung Soll 2", "conversion":"Wert / 10", "type":"K"},
{"index":210, "identifier":"ID_WEB_LIN_HD_2", "description":"Hochdruck 2", "conversion":"Wert / 100", "type":"bar"},
{"index":211, "identifier":"ID_WEB_LIN_ND_2", "description":"Niederdruck 2", "conversion":"Wert / 100", "type":"bar"},
{"index":212, "identifier":"ID_WEB_HDin_2", "description":"Eingang Druckschalter Hochdruck 2", "conversion":"Keine", "type":"Boolean"},
{"index":213, "identifier":"ID_WEB_AVout_2", "description":"Ausgang Abtauventil 2", "conversion":"Keine", "type":"Boolean"},
{"index":214, "identifier":"ID_WEB_VBOout_2", "description":"Ausgang Solepumpe/Ventilator 2", "conversion":"Keine", "type":"Boolean"},
{"index":215, "identifier":"ID_WEB_VD1out_2", "description":"Ausgang Verdichter 1 / 2", "conversion":"Keine", "type":"Boolean"},
{"index":216, "identifier":"ID_WEB_LIN_VDH_out_2", "description":"Ausgang Verdichter Heizung 2", "conversion":"Keine", "type":"Boolean"},
{"index":217, "identifier":"ID_WEB_Switchoff2_file_Nr0", "description":"Grund Abschaltung 0 im Speicher", "conversion":"switchoff_code", "type":"Abschaltcode"},
{"index":218, "identifier":"ID_WEB_Switchoff2_file2_Nr1", "description":"Grund Abschaltung 1 im Speicher", "conversion":"switchoff_code", "type":"Abschaltcode"},
{"index":219, "identifier":"ID_WEB_Switchoff2_file2_Nr2", "description":"Grund Abschaltung 2 im Speicher", "conversion":"switchoff_code", "type":"Abschaltcode"},
{"index":220, "identifier":"ID_WEB_Switchoff2_file2_Nr3", "description":"Grund Abschaltung 3 im Speicher", "conversion":"switchoff_code", "type":"Abschaltcode"},
{"index":221, "identifier":"ID_WEB_Switchoff2_file2_Nr4", "description":"Grund Abschaltung 4 im Speicher", "conversion":"switchoff_code", "type":"Abschaltcode"},
{"index":222, "identifier":"ID_WEB_Switchoff2_file_Time0", "description":"Zeitstempel Abschaltung 0 im Speicher", "conversion":"Keine", "type":"Unix Zeitstempel"},
{"index":223, "identifier":"ID_WEB_Switchoff2_file_Time1", "description":"Zeitstempel Abschaltung 1 im Speicher", "conversion":"Keine", "type":"Unix Zeitstempel"},
{"index":224, "identifier":"ID_WEB_Switchoff2_file_Time2", "description":"Zeitstempel Abschaltung 2 im Speicher", "conversion":"Keine", "type":"Unix Zeitstempel"},
{"index":225, "identifier":"ID_WEB_Switchoff2_file_Time3", "description":"Zeitstempel Abschaltung 3 im Speicher", "conversion":"Keine", "type":"Unix Zeitstempel"},
{"index":226, "identifier":"ID_WEB_Switchoff2_file_Time4", "description":"Zeitstempel Abschaltung 4 im Speicher", "conversion":"Keine", "type":"Unix Zeitstempel"},
{"index":227, "identifier":"ID_WEB_RBE_RT_Ist", "description":"Raumtemperatur Istwert", "conversion":"Wert / 10", "type":"°C"},
{"index":228, "identifier":"ID_WEB_RBE_RT_Soll", "description":"Raumtemperatur Sollwert", "conversion":"Wert / 10", "type":"°C"},
{"index":229, "identifier":"ID_WEB_Temperatur_BW_oben", "description":"Temperatur Brauchwasser Oben", "conversion":"Wert / 10", "type":"°C"},
{"index":230, "identifier":"ID_WEB_Code_WP_akt_2", "description":"Wärmepumpen Typ 2", "conversion":"typecode", "type":"Typenschlüssel"},
{"index":231, "identifier":"ID_WEB_Freq_VD", "sescription":"Verdichterfrequenz", "conversion":"Keine", "type":"Hz"}
];

const status_code_1 = {
0:"Wärmepumpe läuft",
1:"Wärmepumpe steht",
2:"Wärmepumpe kommt",
3:"Fehlercode Speicherplatz 0",
4:"Abtauen",
5:"Warte auf LIN-Verbindung",
6:"Verdichter heizt auf",
7:"Pumpenvorlauf"
}

const status_code_2 = {
0:"Heizbetrieb",
1:"Keine Anforderung",
2:"Netz-Einschaltverzögerung",
3:"Schaltspielsperre",
4:"Sperrzeit",
5:"Brauchwasser",
6:"Info Ausheizprogramm",
7:"Abtauen",
8:"Pumpenvorlauf",
9:"Thermische Desinfektion",
10:"Kühlbetrieb",
12:"Schwimmbad / Photovoltaik",
13:"Heizen ext. Energiequelle",
14:"Brauchwasser ext. Energiequelle",
16:"Durchflussüberachung",
17:"Zweiter Wärmeerzeuger 1 Betrieb"    
}

const built_in = {
0:"nicht verbaut",
1:"verbaut"
}

const operating_state = {
0:"Aus",
1:"Kühlung",
2:"Heizung",
3:"Störung",
4:"Übergang",
5:"Abtauen",
6:"Warte",
7:"Warte",
8:"Übergang",
9:"Stop",
10:"Manuell",
11:"Simulation Start",
12:"EVU Sperre"   
}

const switchoff_codes = {
1:"Wärmepumpe Störung",
2:"Anlagen Störung",
3:"Betriebsart Zweiter Wärmeerzeuger",
4:"EVU-Sperre",
5:"Lauftabtau (nur LW-Geräte)",
6:"Temperatur Einsatzgrenze maximal",
7:"Temperatur Einsatzgrenze minimal (bei LWD reversibel möglicherweise Abschaltung wegen Frostschutz bei Kühlbetrieb - Verdampfungstemperatur zu lange unter 0°C)",
8:"Untere Einsatzgrenze",
9:"Keine Anforderung"
}

const type_codes = [
"ERC",
"SW1",
"SW2",
"WW1",
"WW2",
"L1I",
"L2I",
"L1A",
"L2A",
"KSW",
"KLW",
"SWC",
"LWC",
"L2G",
"WZS",
"L1I407",
"L2I407",
"L1A407",
"L2A407",
"L2G407",
"LWC407",
"L1AREV",
"L2AREV",
"WWC1",
"WWC2",
"L2G404",
"WZW",
"L1S",
"L1H",
"L2H",
"WZWD",
"ERC",
"WWB_20",
"LD5",
"LD7",
"SW 37_45",
"SW 58_69",
"SW 29_56",
"LD5 (230V)",
"LD7 (230 V)",
"LD9",
"LD5 REV",
"LD7 REV",
"LD5 REV 230V",
"LD7 REV 230V",
"LD9 REV 230V",
"SW 291",
"LW SEC",
"HMD 2",
"MSW 4",
"MSW 6",
"MSW 8",
"MSW 10",
"MSW 12",
"MSW 14",
"MSW 17",
"MSW 19",
"MSW 23",
"MSW 26",
"MSW 30",
"MSW 4S",
"MSW 6S",
"MSW 8S",
"MSW 10S",
"MSW 13S",
"MSW 16S",
"MSW2-6S",
"MSW4-16"
];